<a href="https://colab.research.google.com/github/aswinisamantray/Music_Genre_Classification/blob/main/Music_Genre_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q kaggle

In [ ]:
from google.colab import files

# Upload kaggle.json
uploaded = files.upload()

# Move the uploaded file to the correct directory
!mkdir ~/.kaggle
!mv kaggle.json ~/.kaggle/


Saving kaggle.json to kaggle.json


**Importing GTZAN dataset**

In [ ]:
!kaggle datasets download -d andradaolteanu/gtzan-dataset-music-genre-classification

100% 1.21G/1.21G [00:42<00:00, 33.7MB/s]
100% 1.21G/1.21G [00:42<00:00, 30.9MB/s]


**Importing emotions dataset**

In [ ]:
!kaggle datasets download -d ejlok1/toronto-emotional-speech-set-tess

 99% 425M/428M [00:19<00:00, 23.8MB/s]
100% 428M/428M [00:19<00:00, 22.8MB/s]


In [ ]:
!chmod 600 /root/.kaggle/kaggle.json

In [ ]:
!unzip toronto-emotional-speech-set-tess.zip -d root

Streaming output truncated to the last 5000 lines.
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_back_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_bar_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_base_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_bath_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_bean_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_beg_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_bite_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_boat_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_bone_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_book_angry.wav  
  inflating: root/TESS Toronto emotional speech set data/OAF_angry/OAF_

In [ ]:
!unzip gtzan-dataset-music-genre-classification.zip -d root

In [ ]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
from PIL import Image
import pathlib
import csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler #Comment
import keras
import tensorflow as tf
import warnings
warnings. filterwarnings ('ignore')

In [ ]:
!pip install h5py pyyaml
!pip install tf_nightly

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.0/590.0 MB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 46.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 67.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 64.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 40.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 58.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.1/585.1 MB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 110.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 38.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 43.4 MB/s eta 0:00:00
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtypes-0.2.0:
      Successfully uninstalled ml-dtypes-0.2.0
  Attempting uninstall: h5py
    Fo

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
# Define the file path for the CSV file in your Google Drive
%cd /content/

/content/drive


In [ ]:
%cd /content/drive/My Drive/

/content/drive/My Drive


In [ ]:
%ls -lrt

total 870378
-rw------- 1 root root 320133236 May 27  2018 'Substance and Shadow.pptx'
-rw------- 1 root root   3208909 Dec  5  2021 'Electromagnetism assignments.pdf'
-rw------- 1 root root    849278 Dec  8  2021 'Form and passbook.pdf'
-rw------- 1 root root    412632 Dec  8  2021 'Income certificate.pdf'
-rw------- 1 root root    347001 Dec  8  2021  Passbook.pdf
-rw------- 1 root root   7134258 Dec 13  2021 'Assignment week2.pdf'
-rw------- 1 root root    133304 Dec 19  2021  IMG-20211219-WA0055.jpg
-rw------- 1 root root   4020477 Dec 20  2021 'Document 15.pdf'
-rw------- 1 root root   2130140 Dec 21  2021  IMG_20211221_114827.jpg
-rw------- 1 root root   1216331 Jan 26  2022 'ID-12140360 NAME-ASWINI SAMANTRAY Assignment1.mp3'
-rw------- 1 root root   1210688 Jan 29  2022 'ID-12140360 NAME-ASWINI SAMANTRAY Assignment 2.mp3'
drwx------ 2 root root      4096 Feb  5  2022 'Colab Notebooks'/
-rw------- 1 root root    603330 Feb 15  2022 'ID-12140360 NAME-ASWINI SAMANTRAY.pdf'
-rw-----

In [ ]:

header ='filename chroma_stft rmse spectral_centroid spectral_bandwidth rolloff zero_crossing_rate'
for i in range (1,21):
  header +=f' mfcc{i}'
header += ' label'
header=header.split()
header

['filename',
 'chroma_stft',
 'rmse',
 'spectral_centroid',
 'spectral_bandwidth',
 'rolloff',
 'zero_crossing_rate',
 'mfcc1',
 'mfcc2',
 'mfcc3',
 'mfcc4',
 'mfcc5',
 'mfcc6',
 'mfcc7',
 'mfcc8',
 'mfcc9',
 'mfcc10',
 'mfcc11',
 'mfcc12',
 'mfcc13',
 'mfcc14',
 'mfcc15',
 'mfcc16',
 'mfcc17',
 'mfcc18',
 'mfcc19',
 'mfcc20',
 'label']

In [ ]:
file = open('data_emotion.csv', 'w', newline='')
with file:
  writer = csv.writer (file)
  writer.writerow(header)
pd.DataFrame(pd.read_csv('data_emotion.csv'))

Empty DataFrame
Columns: [filename, chroma_stft, rmse, spectral_centroid, spectral_bandwidth, rolloff, zero_crossing_rate, mfcc1, mfcc2, mfcc3, mfcc4, mfcc5, mfcc6, mfcc7, mfcc8, mfcc9, mfcc10, mfcc11, mfcc12, mfcc13, mfcc14, mfcc15, mfcc16, mfcc17, mfcc18, mfcc19, mfcc20, label]
Index: []

[0 rows x 28 columns]

In [ ]:
%cd root/Data/genres_original

[Errno 2] No such file or directory: 'root/Data/genres_original'
/content/drive/My Drive


In [ ]:
genres= 'blues classical country disco hiphop jazz metal pop reggae rock'.split()
count =0

In [ ]:
# dir_em
emotions='OAF_Fear OAF_Pleasant_surprise OAF_Sad OAF_angry OAF_disgust OAF_happy OAF_neutral YAF_angry YAF_disgust YAF_fear YAF_happy YAF_neutral YAF_pleasant_surprised YAF_sad'.split()
count =0

In [ ]:
for genre in genres:
  if genre=='jazz':
    dir=f'root/Data/genres_original/{genre}'
    filenames = os.listdir(dir)
    for filename in  filenames:
      #Sampling of the input:
      y, sr = librosa.load(f'{dir}/{filename}', duration=20)
      #Parameter Extraction:
      chroma_stft =librosa.feature.chroma_stft (y=y, sr=sr)
      rmse = librosa.feature.rms (y=y)
      spec_cent= librosa.feature.spectral_centroid (y=y, sr=sr)
      spec_bw=librosa.feature.spectral_bandwidth (y=y, sr=sr)
      rolloff=librosa.feature.spectral_rolloff (y=y, sr=sr)
      zcr =librosa.feature.zero_crossing_rate(y)
      mfcc=librosa.feature.mfcc(y=y, sr=sr)


      #preparing a input row for csv:
      to_append= f'{filename} {np.mean (chroma_stft)} {np.mean (rmse)} {np.mean (spec_cent)} {np.mean (spec_bw)} {np.mean (rolloff)} {np.mean (zcr)}'
      for e in mfcc:
        to_append += f' {np.mean(e)}'
      to_append += f' {genre}'


      count +=1
      print (f'{count}-{to_append}')
      #writing into csv
      file=open('data.csv', 'a', newline='')
      with file:
        writer= csv.writer (file)
        writer.writerow(to_append.split())


2472-jazz.00024.wav 0.3548615276813507 0.056807294487953186 2118.706027632837 2133.973152626264 4500.202138241371 0.10032027171548724 -204.4772186279297 102.90200805664062 -18.556381225585938 44.93877029418945 -13.73554801940918 25.78609848022461 -16.053924560546875 16.23484230041504 -14.152031898498535 13.869797706604004 -9.261578559875488 10.971891403198242 -2.073326349258423 7.699824810028076 0.3495385944843292 9.7648344039917 -3.2040557861328125 -0.18664243817329407 -3.560361862182617 0.5328925251960754 jazz
2473-jazz.00092.wav 0.25257542729377747 0.05410948395729065 1982.429942415418 2709.3869927040864 4527.081171376522 0.0584974532337587 -296.9296569824219 88.79013061523438 38.550926208496094 32.865543365478516 15.186919212341309 2.0836639404296875 8.310322761535645 7.070192337036133 -6.11738395690918 -6.588421821594238 1.9475754499435425 1.3192510604858398 6.33705997467041 0.9307448267936707 0.8603416681289673 -2.524232864379883 -5.0609540939331055 -1.372259497642517 7.019388675

IsADirectoryError: [Errno 21] Is a directory: 'root/Data/genres_original/jazz/.ipynb_checkpoints'

In [ ]:
for emotion in emotions:
    dir=f'root/TESS Toronto emotional speech set data/{emotion}'
    filenames = os.listdir(dir)
    for filename in  filenames:
      #Sampling of the input:
      y, sr = librosa.load(f'{dir}/{filename}', duration=3, offset=0.5)
      #Parameter Extraction:
      chroma_stft =librosa.feature.chroma_stft (y=y, sr=sr)
      rmse = librosa.feature.rms (y=y)
      spec_cent= librosa.feature.spectral_centroid (y=y, sr=sr)
      spec_bw=librosa.feature.spectral_bandwidth (y=y, sr=sr)
      rolloff=librosa.feature.spectral_rolloff (y=y, sr=sr)
      zcr =librosa.feature.zero_crossing_rate(y)
      mfcc=librosa.feature.mfcc(y=y, sr=sr)


      #preparing a input row for csv:
      to_append= f'{filename} {np.mean (chroma_stft)} {np.mean (rmse)} {np.mean (spec_cent)} {np.mean (spec_bw)} {np.mean (rolloff)} {np.mean (zcr)}'
      for e in mfcc:
        to_append += f' {np.mean(e)}'
      to_append += f' {emotion}'


      count +=1
      print (f'{count}-{to_append}')
      #writing into csv
      file=open('data_emotion.csv', 'a', newline='')
      with file:
        writer= csv.writer (file)
        writer.writerow(to_append.split())


1-OAF_lose_fear.wav 0.24900612235069275 0.03395349159836769 2468.5194255912656 2449.279664715779 4770.1171875 0.10522073412698413 -410.7251892089844 46.20100021362305 11.895796775817871 -3.9932503700256348 -9.558151245117188 8.690463066101074 -8.700502395629883 -5.645627021789551 -25.950740814208984 -8.900874137878418 -16.264097213745117 -4.506706714630127 -6.519975662231445 2.028794050216675 -5.7873735427856445 0.08000355958938599 -0.34031417965888977 3.421962022781372 4.647303581237793 0.9074811935424805 OAF_Fear
2-OAF_reach_fear.wav 0.25301221013069153 0.0221423227339983 2241.839403252204 2306.448626719028 4048.824165962838 0.10641891891891891 -460.21746826171875 50.59569549560547 10.446900367736816 2.682389497756958 2.5432181358337402 7.415571212768555 -7.3022685050964355 -7.525405406951904 -14.908074378967285 -3.5898821353912354 -22.742586135864258 -4.093878746032715 -5.631539344787598 -1.0625079870224 -0.2829747498035431 -0.9684525728225708 0.803864061832428 4.671153545379639 -1.

In [ ]:
data=pd.read_csv('data.csv')
data.head()

filename  chroma_stft      rmse  spectral_centroid  \
0  blues.00010.wav     0.310520  0.144513        1330.397571   
1  blues.00098.wav     0.446590  0.125344        2276.286875   
2  blues.00054.wav     0.451272  0.201647        2053.062270   
3  blues.00090.wav     0.382618  0.129690        1696.818760   
4  blues.00067.wav     0.338506  0.129477        2312.591585   

   spectral_bandwidth      rolloff  zero_crossing_rate       mfcc1  \
0         1449.230986  2516.974146            0.061386 -173.092880   
1         2194.269450  4744.936235            0.127483  -90.072632   
2         2007.351217  4112.454599            0.104958  -56.421837   
3         1991.102103  3635.476663            0.063627 -176.809341   
4         2207.714969  4875.546852            0.114646  -94.056778   

        mfcc2      mfcc3  ...     mfcc12     mfcc13    mfcc14     mfcc15  \
0  143.714157 -24.587389  ...   1.291756  -4.681559 -1.287670  -0.193480   
1  102.098488 -23.654272  ...  14.547861 -10.305332  1.573117 -12.098457   
2  107.230949 -35.676262  ...  14.495609 -11.589649  4.826579  -6.067640   
3  112.235046   8.464725  ...   2.098254  -6.830221  4.133098  -0.099196   
4   99.940796 -19.966311  ...   7.987737 -18.795210  3.295822  -9.143231   

     mfcc16     mfcc17    mfcc18    mfcc19    mfcc20  label  
0 -3.811039   0.365903 -2.624388 -1.591324 -4.236691  blues  
1  5.602223 -11.305524  1.829972 -5.355421  3.403963  blues  
2  3.915451  -8.201335 -0.792196 -5.796125 -2.335963  blues  
3  6.354414  -5.615861 -1.846937  3.988987 -4.740984  blues  
4  6.772897 -12.540654  9.729623 -2.674387 -1.086494  blues  

[5 rows x 28 columns]

In [ ]:
data_emotion=pd.read_csv('data_emotion.csv')
data_emotion.head()

filename  chroma_stft      rmse  spectral_centroid  \
0   OAF_lose_fear.wav     0.249006  0.033953        2468.519426   
1  OAF_reach_fear.wav     0.253012  0.022142        2241.839403   
2   OAF_thin_fear.wav     0.253360  0.023833        2746.708024   
3  OAF_shirt_fear.wav     0.269952  0.029457        2754.895057   
4   OAF_mess_fear.wav     0.277851  0.024954        2635.718137   

   spectral_bandwidth      rolloff  zero_crossing_rate       mfcc1      mfcc2  \
0         2449.279665  4770.117188            0.105221 -410.725189  46.201000   
1         2306.448627  4048.824166            0.106419 -460.217468  50.595695   
2         2530.580329  5071.530762            0.141622 -428.968903  47.486103   
3         2422.593689  4844.778442            0.148987 -376.751160  38.961372   
4         2398.862267  4576.096653            0.139253 -418.454254  52.275082   

       mfcc3  ...    mfcc12    mfcc13    mfcc14    mfcc15    mfcc16    mfcc17  \
0  11.895797  ... -4.506707 -6.519976  2.028794 -5.787374  0.080004 -0.340314   
1  10.446900  ... -4.093879 -5.631539 -1.062508 -0.282975 -0.968453  0.803864   
2  14.383892  ... -8.535769 -6.454487  3.708417 -6.402257 -3.154516 -2.528764   
3   2.014860  ... -6.331210 -5.445251  2.207441 -5.609800 -2.566182 -6.818301   
4  15.281693  ... -8.781083 -6.845668  2.268828 -3.085009 -1.606782 -3.789637   

     mfcc18    mfcc19    mfcc20     label  
0  3.421962  4.647304  0.907481  OAF_Fear  
1  4.671154 -1.315282 -2.168871  OAF_Fear  
2  5.473263 -0.323926 -3.270552  OAF_Fear  
3  6.126344  7.452903  6.491837  OAF_Fear  
4  5.366188  2.015472 -4.568370  OAF_Fear  

[5 rows x 28 columns]

In [ ]:

genre_list = data.iloc[:, -1]
encoder=LabelEncoder()
y = encoder.fit_transform(genre_list)
y.shape, y[:5]

((2520,), array([0, 0, 0, 0, 0]))

In [ ]:

emotion_list = data_emotion.iloc[:, -1]
encoder=LabelEncoder()
y = encoder.fit_transform(emotion_list)
y.shape, y[:5]

((2800,), array([0, 0, 0, 0, 0]))

In [ ]:
data1=data.drop(['filename','label'],axis=1)

In [ ]:
data2=data_emotion.drop(['filename','label'],axis=1)

In [ ]:
scaler=StandardScaler()
X=scaler.fit_transform(np.array(data1,dtype=float))
X

array([[-0.72062683,  0.29454945, -1.08684196, ..., -0.72789352,
         0.19550509, -0.73174099],
       [ 0.91323895,  0.0045017 ,  0.25860779, ...,  0.35246603,
        -0.75812694,  1.0838202 ],
       [ 0.96946485,  1.15903187, -0.05891085, ..., -0.28351405,
        -0.86977905, -0.28009277],
       ...,
       [-0.88768562, -0.37754965,  0.29814906, ..., -1.20993882,
         0.13671505, -0.40297021],
       [-0.79848997, -1.35198974,  0.17129488, ..., -0.39405623,
        -0.53399616, -0.5569344 ],
       [-0.15544909,  1.08768949,  1.26755171, ..., -0.76075967,
        -0.23921149, -0.20231731]])

In [ ]:
scaler=StandardScaler()
X_emotion=scaler.fit_transform(np.array(data2,dtype=float))
X_emotion

array([[-1.32552523,  0.18961909, -0.22603914, ...,  0.05722809,
         1.75323165,  0.16504803],
       [-1.22901245, -0.45235075, -0.61098192, ...,  0.28276954,
         0.36807977, -0.40038582],
       [-1.22064076, -0.36045667,  0.24637431, ...,  0.42759031,
         0.5983791 , -0.60287484],
       ...,
       [-0.51095281,  0.18815476, -0.58502809, ..., -0.80412855,
        -1.08650805, -1.01515157],
       [-0.53714413,  0.24369418, -1.2109764 , ..., -1.03516527,
        -0.52230157, -0.63052405],
       [-0.36806189,  0.20684507,  0.05487153, ..., -0.76497818,
        -1.17511981, -0.32303934]])

In [ ]:

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.20)
print (f'X_train: {X_train. shape}, X_test: {X_test.shape}, y_train: {y_train. shape}, y_test: {y_test.shape}')

X_train: (2016, 26), X_test: (504, 26), y_train: (2016,), y_test: (504,)


In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X_emotion, y, test_size=0.20)
print (f'X_train: {X_train. shape}, X_test: {X_test.shape}, y_train: {y_train. shape}, y_test: {y_test.shape}')

X_train: (2240, 26), X_test: (560, 26), y_train: (2240,), y_test: (560,)


In [ ]:
X_train

array([[-1.88317837, -0.9414414 , -1.3140256 , ...,  0.86742896,
        -0.10759502, -0.13642209],
       [ 0.22874326,  0.9882552 ,  1.75817881, ...,  0.97671815,
        -0.40675211,  2.10157799],
       [ 2.57810168, -0.43341119, -0.89773809, ...,  1.26556592,
         1.24781945,  0.34058242],
       ...,
       [-0.63826206, -1.05427032, -0.94264516, ...,  0.75450312,
         1.04157326, -1.67725971],
       [ 0.39697469, -0.36965564, -0.00352303, ..., -1.13705938,
        -1.20419411,  0.51147292],
       [-1.47934207, -1.00409348, -1.53770186, ...,  0.47311461,
         0.01038973, -0.23730345]])

In [ ]:
X_train.shape[1]

26

In [ ]:

from keras import models,layers
model = models.Sequential([
  layers.Dense (256, activation='relu', input_shape=(X_train.shape[1],)),
  layers.Dropout (0.5),
  layers.Dense (128, activation='relu' ),
  layers.Dropout (0.5),
  layers.Dense (64, activation='relu'),
  layers.Dropout (0.5),
  layers.Dense (14, activation='softmax')
])

In [ ]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
y_train.shape

(2240,)

In [ ]:
model.fit(X_train, y_train, epochs=500, batch_size=64)

Epoch 1/500
35/35 [==============================] - 1s 4ms/step - loss: 2.4414 - accuracy: 0.1862
Epoch 2/500
35/35 [==============================] - 0s 3ms/step - loss: 1.7952 - accuracy: 0.4290
Epoch 3/500
35/35 [==============================] - 0s 3ms/step - loss: 1.1291 - accuracy: 0.6304
Epoch 4/500
35/35 [==============================] - 0s 3ms/step - loss: 0.8078 - accuracy: 0.7397
Epoch 5/500
35/35 [==============================] - 0s 3ms/step - loss: 0.5990 - accuracy: 0.8103
Epoch 6/500
35/35 [==============================] - 0s 3ms/step - loss: 0.4809 - accuracy: 0.8487
Epoch 7/500
35/35 [==============================] - 0s 3ms/step - loss: 0.3979 - accuracy: 0.8777
Epoch 8/500
35/35 [==============================] - 0s 3ms/step - loss: 0.3629 - accuracy: 0.8844
Epoch 9/500
35/35 [==============================] - 0s 3ms/step - loss: 0.3166 - accuracy: 0.8946
Epoch 10/500
35/35 [==============================] - 0s 4ms/step - loss: 0.2723 - accuracy: 0.9174
Epoch 11/

In [ ]:

test_loss, test_acc= model.evaluate(X_test,y_test)

16/16 [==============================] - 0s 2ms/step - loss: 0.2330 - accuracy: 0.9623


In [ ]:
test_loss, test_acc= model.evaluate(X_test,y_test)

18/18 [==============================] - 0s 4ms/step - loss: 0.0640 - accuracy: 0.9964


In [ ]:
y_pred = model.predict(X_test)

18/18 [==============================] - 0s 2ms/step


In [ ]:
X_test.shape

(504, 26)

In [ ]:
y_test.shape

(504,)

In [ ]:
import numpy as np

class BroadLearning:
    def __init__(self, num_mapped_features, num_nonlinear_mappings):
        self.num_mapped_features = num_mapped_features
        self.num_nonlinear_mappings = num_nonlinear_mappings
        self.W_e = np.random.randn(num_mapped_features, num_mapped_features)
        self.beta_e = np.random.randn(num_mapped_features)
        self.W_h = np.random.randn(num_mapped_features, num_nonlinear_mappings)
        self.beta_h = np.random.randn(num_nonlinear_mappings)
        self.W = None

    def linear_projection(self, X):
        Z = []
        for i in range(self.num_mapped_features):
            Z_i = np.dot(X, self.W_e[i]) + self.beta_e[i]
            Z.append(Z_i)
        return np.array(Z)

    def nonlinear_mapping(self, Z):
        H = []
        for j in range(self.num_nonlinear_mappings):
            H_j = np.tanh(np.dot(Z, self.W_h[:, j]) + self.beta_h[j])
            H.append(H_j)
        return np.array(H)

    def train(self, X, Y):
        Z = self.linear_projection(X)
        H = self.nonlinear_mapping(Z)
        combined_features = np.concatenate((Z, H), axis=1)
        self.W = np.linalg.pinv(combined_features) @ Y

    def predict(self, X_cap):
        Z_cap = self.linear_projection(X_cap)
        H_cap = self.nonlinear_mapping(Z_cap)
        combined_features_cap = np.concatenate((Z_cap, H_cap), axis=1)
        Y_cap = combined_features_cap @ self.W
        return Y_cap


In [ ]:
# Set num_mapped_features based on the number of features extracted by the RCNN model
num_mapped_features = X_train.shape[1]  # Assuming X_train_features is your extracted features

# Set num_nonlinear_mappings
num_nonlinear_mappings = 2  # Example value, you can experiment with different values

# Initialize Broad Learning model
broad_learning_model = BroadLearning(num_mapped_features=num_mapped_features, num_nonlinear_mappings=num_nonlinear_mappings)

# Train the Broad Learning model
broad_learning_model.train(X_train, y_train)

# Predict tags for test data
Y_pred = broad_learning_model.predict(X_test)


ValueError: shapes (26,2016) and (26,) not aligned: 2016 (dim 1) != 26 (dim 0)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# Compute evaluation metrics
threshold = 0.5
Y_pred_binary = (y_pred > threshold).astype(int)
accuracy = accuracy_score(y_test, Y_pred_binary)
precision = precision_score(y_test, Y_pred_binary, average='binary')
recall = recall_score(y_test, Y_pred_binary, average='binary')
f1 = f1_score(y_test, Y_pred_binary, average='binary')

# Print evaluation metrics
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

ValueError: Classification metrics can't handle a mix of multiclass and multilabel-indicator targets

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Reshape y_test if necessary
y_test_reshaped = y_test.flatten()  # Reshape to a 1D array

# Extract labels from y_pred if necessary
y_pred_labels = np.argmax(y_pred, axis=1)

# 1. Accuracy
accuracy = accuracy_score(y_test_reshaped, y_pred_labels)
print("Accuracy:", accuracy)

# 2. Confusion Matrix
conf_matrix = confusion_matrix(y_test_reshaped, y_pred_labels)
print("Confusion Matrix:")
print(conf_matrix)

# 3. Precision, Recall, and F1-score
print("Classification Report:")
print(classification_report(y_test_reshaped, y_pred_labels))

# Other evaluation metrics...


Accuracy: 0.9623015873015873
Confusion Matrix:
[[82  0  0  0  0  0  0  0  0  0]
 [ 0 96  0  0  0  0  0  0  0  0]
 [ 0  0 83  0  0  0  0  0  0  0]
 [ 0  0  0 78  0  0  0  0  0  0]
 [ 0  0  0  0 83  0  0  0  0  0]
 [ 0  0  0  0  0 18  0  0  0  0]
 [ 0  0  0  0  0  0 12  0  0  0]
 [ 0  0  1  3  0  0  0 12  0  2]
 [ 0  0  0  0  2  1  1  1 13  0]
 [ 2  0  1  3  1  0  1  0  0  8]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        82
           1       1.00      1.00      1.00        96
           2       0.98      1.00      0.99        83
           3       0.93      1.00      0.96        78
           4       0.97      1.00      0.98        83
           5       0.95      1.00      0.97        18
           6       0.86      1.00      0.92        12
           7       0.92      0.67      0.77        18
           8       1.00      0.72      0.84        18
           9       0.80      0.50      0.62        16

   

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Reshape y_test if necessary
y_test_reshaped = y_test.flatten()  # Reshape to a 1D array

# Extract labels from y_pred if necessary
y_pred_labels = np.argmax(y_pred, axis=1)

# 1. Accuracy
accuracy = accuracy_score(y_test_reshaped, y_pred_labels)
print("Accuracy:", accuracy)

# 2. Confusion Matrix
conf_matrix = confusion_matrix(y_test_reshaped, y_pred_labels)
print("Confusion Matrix:")
print(conf_matrix)

# 3. Precision, Recall, and F1-score
print("Classification Report:")
print(classification_report(y_test_reshaped, y_pred_labels))

# Other evaluation metrics...


Accuracy: 0.9964285714285714
Confusion Matrix:
[[36  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 37  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 42  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 47  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 45  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 37  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 39  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 36  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 44  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 50]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        40
           2       1.00      1.00      1.00        37
           3       1.00      1.00      1.00        42
           4       1.00     

In [ ]:
!kaggle datasets download -d nelgiriyewithana/emotions

100% 15.7M/15.7M [00:01<00:00, 17.3MB/s]
100% 15.7M/15.7M [00:01<00:00, 9.33MB/s]


In [ ]:
!kaggle datasets download -d arashnic/dance-with-machine-learning

  0% 0.00/1.74k [00:00<?, ?B/s]
100% 1.74k/1.74k [00:00<00:00, 3.68MB/s]


In [ ]:
!unzip dance-with-machine-learning.zip -d root

Archive:  dance-with-machine-learning.zip
  inflating: root/youtube_links_test.txt  
  inflating: root/youtube_links_val.txt  
